/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaCliente;
import CapaNegocio.*;

import javax.swing.JOptionPane;
/**
 *
 * @author Czleb
 */
public class MenuOpcionesPrincipales extends javax.swing.JFrame {
public static String numeroPasaporteRegistrar;
public static String numeroPasaporteModificarDatos;
public static String numeroPasaporteModificarForm;
public static int numeroVueloRegistrar;

    //Creacion de arreglo estatico
    
   
    
    //Creacion de metodos estaticos
    


    /**
     * Creates new form MenuOpcionesPrincipales
     */
    public MenuOpcionesPrincipales() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegistar = new javax.swing.JButton();
        botonAgregarVuelo = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        botonMostrarTodos = new javax.swing.JButton();
        botonModifiicarPersonales = new javax.swing.JButton();
        botonModificarForm = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        logoPequenio = new javax.swing.JLabel();
        logoPequenio2 = new javax.swing.JLabel();
        logoPequenio3 = new javax.swing.JLabel();
        logoPequenio4 = new javax.swing.JLabel();
        logoPequenio5 = new javax.swing.JLabel();
        logoPequenio6 = new javax.swing.JLabel();
        logoTop = new javax.swing.JLabel();
        botonMostrarVuelos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(640, 400));

        botonRegistar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonRegistar.setText("Registrar pasajero");
        botonRegistar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistarActionPerformed(evt);
            }
        });

        botonAgregarVuelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonAgregarVuelo.setText("Agregar vuelo");
        botonAgregarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarVueloActionPerformed(evt);
            }
        });

        botonMostrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonMostrar.setText("Mostrar pasajero");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });

        botonMostrarTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonMostrarTodos.setText("Mostrar todos los pasajeros ");
        botonMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTodosActionPerformed(evt);
            }
        });

        botonModifiicarPersonales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonModifiicarPersonales.setText("Modificar datos personales");
        botonModifiicarPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModifiicarPersonalesActionPerformed(evt);
            }
        });

        botonModificarForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonModificarForm.setText("Modificar formulario");
        botonModificarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarFormActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        logoPequenio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoPequenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoGrande.png"))); // NOI18N

        logoPequenio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoGrande.png"))); // NOI18N

        logoPequenio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoGrande.png"))); // NOI18N

        logoPequenio4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        logoPequenio4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        logoPequenio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoGrande.png"))); // NOI18N

        logoPequenio5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        logoPequenio5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoGrande.png"))); // NOI18N

        logoPequenio6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        logoPequenio6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoGrande.png"))); // NOI18N

        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura.JPG"))); // NOI18N

        botonMostrarVuelos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonMostrarVuelos.setText("Mostrar vuelos");
        botonMostrarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarVuelosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoPequenio4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoPequenio6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonMostrarTodos)
                            .addComponent(botonModifiicarPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonModificarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonMostrarVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoPequenio5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(logoTop)
                        .addGap(63, 63, 63)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoPequenio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoPequenio3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoPequenio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(logoPequenio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(logoTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(logoPequenio5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonRegistar)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logoPequenio3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(botonAgregarVuelo)
                            .addGap(18, 18, 18)
                            .addComponent(botonMostrarVuelos)
                            .addGap(18, 18, 18)
                            .addComponent(botonMostrar)
                            .addGap(18, 18, 18)
                            .addComponent(botonMostrarTodos))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(logoPequenio4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(botonModifiicarPersonales)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonModificarForm)
                        .addGap(18, 18, 18)
                        .addComponent(botonSalir)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addComponent(logoPequenio6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoPequenio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarFormActionPerformed
        // TODO add your handling code here:
          String n = JOptionPane.showInputDialog(null, "Ingrese el numero de pasaporte del pasajero a modificar su formulario:");
        if(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, n)!=null){
        numeroPasaporteModificarForm = n;
        ModificarFormulario m1 = new ModificarFormulario();
        //m1.llenarConDatosAnteriores();
        m1.setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "ERROR.PASAJERO NO EXISTE EN EL SISTEMA.");
        }
    }//GEN-LAST:event_botonModificarFormActionPerformed

    private void botonRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "RECUERDE VERIFICAR QUE EXISTAN VUELOS REGISTRADOS EN EL SISTEMA.");
        String n = JOptionPane.showInputDialog(null, "Ingrese el numero de pasaporte del pasajero a registrar");
        numeroPasaporteRegistrar = n;
        if(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, n) == null&& PantallaInicial.validadorDeCedula(numeroPasaporteRegistrar)==true){
        RegistrarPasajero r1 = new RegistrarPasajero();
        r1.setVisible(true);
        this.setVisible(false);
        }else if(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, n) != null){
             JOptionPane.showMessageDialog(null, "ERROR. PASAJERO YA EXISTE");
        }else if(PantallaInicial.validadorDeCedula(numeroPasaporteRegistrar)==false){
             JOptionPane.showMessageDialog(null, "ERROR.NUMERO DE PASAPORTE INGRESADO ES INVÁLIDO.");
        }
    }//GEN-LAST:event_botonRegistarActionPerformed

    private void botonAgregarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarVueloActionPerformed
        // TODO add your handling code here:
     String n = JOptionPane.showInputDialog(null, "Ingrese el numero de vuelo a registrar:");
     try{
     numeroVueloRegistrar = Integer.parseInt(n);
      if(PantallaInicial.buscarVuelo(PantallaInicial.vuelos, Integer.parseInt(n))== null && PantallaInicial.isNumeric(n)==true){
     RegistrarVuelo r1 = new RegistrarVuelo();
     this.setVisible(false);
     r1.setVisible(true);
      }else if(PantallaInicial.buscarVuelo(PantallaInicial.vuelos, Integer.parseInt(n))!= null){
             JOptionPane.showMessageDialog(null, "ERROR. VUELO YA EXISTE");
      }
     }catch(NumberFormatException e){
         JOptionPane.showMessageDialog(null, "POR FAVOR INGRESE UN NUMERO.");
     }
    }//GEN-LAST:event_botonAgregarVueloActionPerformed
    
    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        // TODO add your handling code here:
      String n = JOptionPane.showInputDialog(null, "Ingrese el numero de pasaporte del pasajero a mostrar");
      PantallaInicial.mostrarPasajero(PantallaInicial.pasajeros, n);
       if(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, n) == null){
             JOptionPane.showMessageDialog(null, "ERROR. PASAJERO NO EXISTE");
       }
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void botonMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTodosActionPerformed
        // TODO add your handling code here:
       //MostrarPasaportesRegistrados m1 = new MostrarPasaportesRegistrados();
       //this.setVisible(false);
      // m1.setVisible(true);
       PantallaInicial.mostrarPasaportesRegistrados(PantallaInicial.pasajeros);
    }//GEN-LAST:event_botonMostrarTodosActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonModifiicarPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModifiicarPersonalesActionPerformed
        // TODO add your handling code here:
     String n = JOptionPane.showInputDialog(null, "Ingrese el numero de pasaporte del pasajero a modificar");
        if(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, n)!=null){
        numeroPasaporteModificarDatos = n;
        ModificarPasajero m1 = new ModificarPasajero();
        m1.llenarConDatosAnteriores();
        m1.setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "ERROR.PASAJERO NO EXISTE EN EL SISTEMA.");
        }
     
    }//GEN-LAST:event_botonModifiicarPersonalesActionPerformed

    private void botonMostrarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarVuelosActionPerformed
        // TODO add your handling code here:
        PantallaInicial.mostrarVuelosRegistrados(PantallaInicial.vuelos);
    }//GEN-LAST:event_botonMostrarVuelosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpcionesPrincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpcionesPrincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpcionesPrincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpcionesPrincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpcionesPrincipales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarVuelo;
    private javax.swing.JButton botonModificarForm;
    private javax.swing.JButton botonModifiicarPersonales;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonMostrarTodos;
    private javax.swing.JButton botonMostrarVuelos;
    private javax.swing.JButton botonRegistar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel logoPequenio;
    private javax.swing.JLabel logoPequenio2;
    private javax.swing.JLabel logoPequenio3;
    private javax.swing.JLabel logoPequenio4;
    private javax.swing.JLabel logoPequenio5;
    private javax.swing.JLabel logoPequenio6;
    private javax.swing.JLabel logoTop;
    // End of variables declaration//GEN-END:variables
}
