/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaCliente;
import CapaNegocio.*;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Czleb
 */
public class ModificarPasajero extends javax.swing.JFrame {

    /**
     * Creates new form ModificarPasajero
     */
    public ModificarPasajero() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesGenero = new javax.swing.ButtonGroup();
        logoTop = new javax.swing.JLabel();
        labelNombres = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelNacionalidad = new javax.swing.JLabel();
        labelDestinoPasajero = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelNumContacto = new javax.swing.JLabel();
        labelCiudadProviene = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        btnMasculino = new javax.swing.JRadioButton();
        btnFemenino = new javax.swing.JRadioButton();
        ingresaNombreModif = new javax.swing.JTextField();
        ingresaApellidoModif = new javax.swing.JTextField();
        ingresaNacionalidadModif = new javax.swing.JTextField();
        ingresaDestinoModif = new javax.swing.JTextField();
        ingresaCorreoModif = new javax.swing.JTextField();
        ingresaNumContactoModif = new javax.swing.JTextField();
        ingresaCiudadModif = new javax.swing.JTextField();
        botonGuardarYSalir = new javax.swing.JButton();
        labelPasaporteNuevo = new javax.swing.JLabel();
        ingresaPasaporteNuevo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificacion de datos personales de un pasajero");

        logoTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura.JPG"))); // NOI18N

        labelNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombres.setText("Nombre:");

        labelApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelApellidos.setText("Apellidos:");

        labelNacionalidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNacionalidad.setText("Nacionalidad:");

        labelDestinoPasajero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDestinoPasajero.setText("Destino del pasajero:");

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEmail.setText("Email:");

        labelNumContacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNumContacto.setText("Numero de contacto:");

        labelCiudadProviene.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCiudadProviene.setText("Ciudad de donde proviene:");

        labelGenero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelGenero.setText("Genero:");

        botonesGenero.add(btnMasculino);
        btnMasculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMasculino.setSelected(true);
        btnMasculino.setText("Masculino");

        botonesGenero.add(btnFemenino);
        btnFemenino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFemenino.setText("Femenino");
        btnFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemeninoActionPerformed(evt);
            }
        });

        ingresaNombreModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresaNombreModifActionPerformed(evt);
            }
        });

        botonGuardarYSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonGuardarYSalir.setText("Guardar y Salir");
        botonGuardarYSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarYSalirActionPerformed(evt);
            }
        });

        labelPasaporteNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPasaporteNuevo.setText("Pasaporte nuevo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNacionalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingresaNacionalidadModif))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDestinoPasajero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingresaDestinoModif))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNombres)
                            .addComponent(labelApellidos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ingresaNombreModif)
                            .addComponent(ingresaApellidoModif, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEmail)
                        .addGap(18, 18, 18)
                        .addComponent(ingresaCorreoModif, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNumContacto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ingresaNumContactoModif, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelGenero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMasculino))
                                .addComponent(labelCiudadProviene))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ingresaCiudadModif, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(btnFemenino)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelPasaporteNuevo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingresaPasaporteNuevo))))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoTop)
                .addGap(305, 305, 305))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombres)
                    .addComponent(labelNumContacto)
                    .addComponent(ingresaNombreModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresaNumContactoModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidos)
                    .addComponent(ingresaApellidoModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCiudadProviene)
                    .addComponent(ingresaCiudadModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNacionalidad)
                    .addComponent(ingresaNacionalidadModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGenero)
                    .addComponent(btnMasculino)
                    .addComponent(btnFemenino))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDestinoPasajero)
                    .addComponent(ingresaDestinoModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPasaporteNuevo)
                    .addComponent(ingresaPasaporteNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresaCorreoModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail)
                    .addComponent(botonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFemeninoActionPerformed

    private void ingresaNombreModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresaNombreModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaNombreModifActionPerformed

    private void botonGuardarYSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarYSalirActionPerformed
        // TODO add your handling code here:
         MenuOpcionesPrincipales m1 = new MenuOpcionesPrincipales();
         
        if(validarIngresoNombre()&&validarIngresoApellidos()&&validarNumeroContacto()&&validarIngresoNacionalidad()&&validarIngresoDestino()&&validarIngresoCiudadOrigen()&&validarEmail()&&validarNumPasaporteNuevo())
        {
        PantallaInicial.modificarUsuario(PantallaInicial.pasajeros, ingresaNombreModif.getText(), ingresaApellidoModif.getText(), ingresaNacionalidadModif.getText(),  ingresaCiudadModif.getText(), ingresaCorreoModif.getText(),ingresaNumContactoModif.getText(), MenuOpcionesPrincipales.numeroPasaporteModificarDatos,ingresaPasaporteNuevo.getText(),validarGenero(), ingresaDestinoModif.getText());
        this.setVisible(false);
        m1.setVisible(true);
        }else if (validarIngresoNombre()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE NOMBRES.");
        }else if(validarIngresoApellidos()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE APELLIDOS.");
        }else if(validarNumeroContacto()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE NUMERO DE CONTACTO.");
        }else if(validarIngresoNacionalidad()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE NACIONALIDAD.");
        }else if(validarIngresoDestino()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE CIUDAD DE DESTINO.");
        }else if(validarIngresoCiudadOrigen()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE CIUDAD DE ORIGEN.");
        }else if(validarEmail()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE EMAIL.");
        }else if(validarNumPasaporteNuevo()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE  NUMERO PASAPORTE.");
        }else{
            JOptionPane.showMessageDialog(null, "ERROR INESPERADO");
        }
        
    }//GEN-LAST:event_botonGuardarYSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPasajero().setVisible(true);
            }
        });
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de nombres sea valido
     * @return boolean
     */
    public boolean validarIngresoNombre(){
        boolean validacion= true;
        if(ingresaNombreModif.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresaNombreModif.getText())==true){
            validacion = false;
        }
        return validacion;
    }
 /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de apellidos sea valido
     * @return boolean
     */
    public boolean validarIngresoApellidos(){
        boolean validacion= true;
        if(ingresaApellidoModif.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresaApellidoModif.getText())==true){
            validacion = false;
        }
        return validacion;
    }
        /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de nacionalidad sea valido
     * @return boolean
     */
    public boolean validarIngresoNacionalidad(){
        boolean validacion= true;
        if(ingresaNacionalidadModif.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresaNacionalidadModif.getText())==true){
            validacion = false;
        }
        return validacion;
    }
     /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de ciudad destino sea valido
     * @return boolean
     */
    public boolean validarIngresoDestino(){
        boolean validacion= true;
        if(ingresaDestinoModif.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresaDestinoModif.getText())==true){
            validacion = false;
        }
        return validacion;
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de ciudad de origen sea valido
     * @return boolean
     */
    public boolean validarIngresoCiudadOrigen(){
        boolean validacion= true;
        if(ingresaCiudadModif.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresaCiudadModif.getText())==true){
            validacion = false;
        }
        return validacion;
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de genero
     * @return boolean
     */
    public boolean validarGenero(){
       boolean validar = true;
      if(btnMasculino.isSelected()){
          validar = true;
      }else{
          validar = false;
     
    }
      return validar;
    }
      //}else if(botonMasculino.isSelected()== false && botonFemenino.isSelected() ==false){
      //validacionGenero = 0;
  
      
     /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de email sea valido
     * @return boolean
     */
    public boolean validarEmail(){
        Pattern rfc2822 = Pattern.compile("^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
					);
        boolean validacion= true;
        if(ingresaCorreoModif.getText().isEmpty()==true){
            validacion = false;
        }
         //Bloque de validacion para email usando clases PATTERN y MATCHER
	if(!rfc2822.matcher(ingresaCorreoModif.getText()).matches()) {
	validacion = false;
			} 
        return validacion;
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de numero contacto sea valido
     * @return boolean
     */
    public boolean validarNumeroContacto(){
        boolean validacion= true;
        if(ingresaNumContactoModif.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresaNumContactoModif.getText())==false){
            validacion = false;
        }
        if(ingresaNumContactoModif.getText().length()<10 || ingresaNumContactoModif.getText().length()>15){
            validacion = false;
        }
        return validacion;
        
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de pasaportes sea valido
     * @return boolean
     */
    public boolean validarNumPasaporteNuevo(){
        boolean validacion= true;
        if(ingresaPasaporteNuevo.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresaPasaporteNuevo.getText())==false){
            validacion = false;
        }
        if(PantallaInicial.validadorDeCedula(ingresaPasaporteNuevo.getText())==false){
            validacion = false;
        }
        return validacion;
        
    }
    /**
     * Metodo que no retorna, y rellena los campos con lo anteriormente registrado
     * @return void
     */
    public void llenarConDatosAnteriores(){
        ingresaApellidoModif.setText(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteModificarDatos).getApellido());
        ingresaNombreModif.setText(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteModificarDatos).getNombre());
        ingresaCiudadModif.setText(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteModificarDatos).getCiudadOrigenViaje());
        ingresaDestinoModif.setText(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteModificarDatos).getDestinoFinalViaje());
        ingresaPasaporteNuevo.setText(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteModificarDatos).getNumeroPasaporte());
        ingresaNumContactoModif.setText(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteModificarDatos).getNumeroContacto());
        ingresaCorreoModif.setText(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteModificarDatos).getCorreoElectronico());
        if(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteModificarDatos).getGenero().equals("Masculino")){
            btnMasculino.setSelected(true);
        }else{
            btnFemenino.setSelected(true);
        }
        ingresaNacionalidadModif.setText(PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteModificarDatos).getNacionalidad());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarYSalir;
    private javax.swing.ButtonGroup botonesGenero;
    private javax.swing.JRadioButton btnFemenino;
    private javax.swing.JRadioButton btnMasculino;
    private javax.swing.JTextField ingresaApellidoModif;
    private javax.swing.JTextField ingresaCiudadModif;
    private javax.swing.JTextField ingresaCorreoModif;
    private javax.swing.JTextField ingresaDestinoModif;
    private javax.swing.JTextField ingresaNacionalidadModif;
    private javax.swing.JTextField ingresaNombreModif;
    private javax.swing.JTextField ingresaNumContactoModif;
    private javax.swing.JTextField ingresaPasaporteNuevo;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCiudadProviene;
    private javax.swing.JLabel labelDestinoPasajero;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNacionalidad;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel labelNumContacto;
    private javax.swing.JLabel labelPasaporteNuevo;
    private javax.swing.JLabel logoTop;
    // End of variables declaration//GEN-END:variables
}
