/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaCliente;


import CapaNegocio.*;
import java.util.Date;
import javax.swing.JOptionPane;
import java.lang.String; 
import java.util.regex.Pattern;
/**
 *
 * @author Czleb
 */
public class RegistrarPasajero extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPasajero
     */
    public RegistrarPasajero() {
        initComponents();
        this.setLocationRelativeTo(null);
          this.setResizable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesFiebre = new javax.swing.ButtonGroup();
        grupoBotonesMalestar = new javax.swing.ButtonGroup();
        grupoBotoesDolorCabeza = new javax.swing.ButtonGroup();
        grupoBotonesTos = new javax.swing.ButtonGroup();
        grupoBotonesDificultades = new javax.swing.ButtonGroup();
        grupoBotonesGenero = new javax.swing.ButtonGroup();
        grupoBotonesResultado = new javax.swing.ButtonGroup();
        logoTop = new javax.swing.JLabel();
        labelNombres = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelNacionalidad = new javax.swing.JLabel();
        labelNumContacto = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        ingresoNombres = new javax.swing.JTextField();
        ingresoApellidos = new javax.swing.JTextField();
        ingresoNacionalidad = new javax.swing.JTextField();
        ingresoDestinoPasajero = new javax.swing.JTextField();
        ingresoNumContacto = new javax.swing.JTextField();
        ingresoNumeroVuelo = new javax.swing.JTextField();
        botonMasculino = new javax.swing.JRadioButton();
        botonFemenino = new javax.swing.JRadioButton();
        labelEmail = new javax.swing.JLabel();
        ingresoEmail = new javax.swing.JTextField();
        labelTituloSintomatologia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fiebreSi = new javax.swing.JRadioButton();
        fiebreNo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        malestarSi = new javax.swing.JRadioButton();
        malestarNo = new javax.swing.JRadioButton();
        dolorCabezaSi = new javax.swing.JRadioButton();
        dolorCabezaNo = new javax.swing.JRadioButton();
        tosSi = new javax.swing.JRadioButton();
        tosNo = new javax.swing.JRadioButton();
        dificultadesSi = new javax.swing.JRadioButton();
        dificultadesNo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        resultadoPositivo = new javax.swing.JRadioButton();
        resultadoNegativo = new javax.swing.JRadioButton();
        ingresaDia = new javax.swing.JTextField();
        ingresaMes = new javax.swing.JTextField();
        ingresaAnio = new javax.swing.JTextField();
        botonGuardarYSalir = new javax.swing.JButton();
        labelNumeroVuelo = new javax.swing.JLabel();
        ingresoCiudadPasajero1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar pasajeros ");
        setSize(new java.awt.Dimension(565, 700));

        logoTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura.JPG"))); // NOI18N

        labelNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombres.setText("Nombres:");
        labelNombres.setToolTipText("");

        labelApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelApellidos.setText("Apellidos:");
        labelApellidos.setToolTipText("");

        labelNacionalidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNacionalidad.setText("Nacionalidad:");
        labelNacionalidad.setToolTipText("");

        labelNumContacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNumContacto.setText("Numero de contacto:");
        labelNumContacto.setToolTipText("");

        labelCiudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCiudad.setText("Ciudad de donde proviene:");
        labelCiudad.setToolTipText("");

        labelDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDestino.setText("Destino del pasajero:");
        labelDestino.setToolTipText("");

        labelGenero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelGenero.setText("Genero:");
        labelGenero.setToolTipText("");

        ingresoNombres.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ingresoNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoNombresFocusGained(evt);
            }
        });
        ingresoNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNombresActionPerformed(evt);
            }
        });

        ingresoApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoApellidosFocusGained(evt);
            }
        });

        ingresoNacionalidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoNacionalidadFocusGained(evt);
            }
        });

        ingresoDestinoPasajero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoDestinoPasajeroFocusGained(evt);
            }
        });

        ingresoNumContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoNumContactoFocusGained(evt);
            }
        });

        ingresoNumeroVuelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoNumeroVueloFocusGained(evt);
            }
        });
        ingresoNumeroVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNumeroVueloActionPerformed(evt);
            }
        });

        grupoBotonesGenero.add(botonMasculino);
        botonMasculino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonMasculino.setSelected(true);
        botonMasculino.setText("Masculino");
        botonMasculino.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                botonMasculinoStateChanged(evt);
            }
        });
        botonMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasculinoActionPerformed(evt);
            }
        });

        grupoBotonesGenero.add(botonFemenino);
        botonFemenino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonFemenino.setText("Femenino");
        botonFemenino.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                botonFemeninoStateChanged(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEmail.setText("E-mail:");
        labelEmail.setToolTipText("");

        ingresoEmail.setText("ejemplo@example.com");

        labelTituloSintomatologia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloSintomatologia.setText("SINTOMATOLOGIA: (Ingrese aquellos sintomas que presente)");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Fiebre:");

        grupoBotonesFiebre.add(fiebreSi);
        fiebreSi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fiebreSi.setSelected(true);
        fiebreSi.setText("Si");
        fiebreSi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fiebreSiStateChanged(evt);
            }
        });
        fiebreSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiebreSiActionPerformed(evt);
            }
        });

        grupoBotonesFiebre.add(fiebreNo);
        fiebreNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fiebreNo.setText("No");
        fiebreNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fiebreNoStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tos Seca:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Malestar general:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Dificultades respiratorias:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Dolor de cabeza:");

        grupoBotonesMalestar.add(malestarSi);
        malestarSi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        malestarSi.setSelected(true);
        malestarSi.setText("Si");
        malestarSi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                malestarSiStateChanged(evt);
            }
        });

        grupoBotonesMalestar.add(malestarNo);
        malestarNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        malestarNo.setText("No");
        malestarNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                malestarNoStateChanged(evt);
            }
        });

        grupoBotoesDolorCabeza.add(dolorCabezaSi);
        dolorCabezaSi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dolorCabezaSi.setSelected(true);
        dolorCabezaSi.setText("Si");
        dolorCabezaSi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dolorCabezaSiStateChanged(evt);
            }
        });

        grupoBotoesDolorCabeza.add(dolorCabezaNo);
        dolorCabezaNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dolorCabezaNo.setText("No");
        dolorCabezaNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dolorCabezaNoStateChanged(evt);
            }
        });

        grupoBotonesTos.add(tosSi);
        tosSi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tosSi.setSelected(true);
        tosSi.setText("Si");
        tosSi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tosSiStateChanged(evt);
            }
        });

        grupoBotonesTos.add(tosNo);
        tosNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tosNo.setText("No");
        tosNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tosNoStateChanged(evt);
            }
        });

        grupoBotonesDificultades.add(dificultadesSi);
        dificultadesSi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dificultadesSi.setSelected(true);
        dificultadesSi.setText("Si");
        dificultadesSi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dificultadesSiStateChanged(evt);
            }
        });

        grupoBotonesDificultades.add(dificultadesNo);
        dificultadesNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dificultadesNo.setText("No");
        dificultadesNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dificultadesNoStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("PRUEBA PCR: (Ingrese los datos solicitados a partir de la Prueba PCR realizada)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Dia:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mes:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Año:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Resultado:");

        grupoBotonesResultado.add(resultadoPositivo);
        resultadoPositivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultadoPositivo.setSelected(true);
        resultadoPositivo.setText("Postivo");
        resultadoPositivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                resultadoPositivoStateChanged(evt);
            }
        });

        grupoBotonesResultado.add(resultadoNegativo);
        resultadoNegativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultadoNegativo.setText("Negativo");
        resultadoNegativo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                resultadoNegativoStateChanged(evt);
            }
        });

        ingresaDia.setText("dd");
        ingresaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresaDiaActionPerformed(evt);
            }
        });

        ingresaMes.setText("mm");

        ingresaAnio.setText("aaaa");

        botonGuardarYSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonGuardarYSalir.setText("GUARDAR Y SALIR");
        botonGuardarYSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarYSalirActionPerformed(evt);
            }
        });

        labelNumeroVuelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNumeroVuelo.setText("Numero de vuelo:");
        labelNumeroVuelo.setToolTipText("");

        ingresoCiudadPasajero1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoCiudadPasajero1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ingresaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingresaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTituloSintomatologia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fiebreSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fiebreNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(malestarSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(malestarNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dolorCabezaSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dolorCabezaNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ingresaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(labelEmail)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ingresoEmail))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(labelDestino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ingresoDestinoPasajero))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(labelNacionalidad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ingresoNacionalidad))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(labelApellidos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ingresoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(labelNombres)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ingresoNombres)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNumContacto)
                                            .addComponent(labelCiudad)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelGenero)
                                                .addGap(18, 18, 18)
                                                .addComponent(botonMasculino))
                                            .addComponent(labelNumeroVuelo))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tosSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tosNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dificultadesSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dificultadesNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoPositivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoNegativo))
                            .addComponent(botonFemenino)
                            .addComponent(ingresoNumContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(ingresoCiudadPasajero1)
                            .addComponent(ingresoNumeroVuelo))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(logoTop)
                                .addGap(306, 306, 306))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(383, 383, 383))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNumContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoCiudadPasajero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMasculino)
                    .addComponent(botonFemenino))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoDestinoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNumeroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTituloSintomatologia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiebreSi)
                    .addComponent(fiebreNo)
                    .addComponent(jLabel2)
                    .addComponent(tosSi)
                    .addComponent(tosNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(malestarSi)
                    .addComponent(malestarNo)
                    .addComponent(dificultadesSi)
                    .addComponent(dificultadesNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dolorCabezaSi)
                    .addComponent(dolorCabezaNo))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ingresaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(resultadoPositivo)
                        .addComponent(resultadoNegativo)
                        .addComponent(ingresaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ingresaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

 
    private void ingresoNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNombresActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ingresoNombresActionPerformed

    private void fiebreSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiebreSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiebreSiActionPerformed

    private void ingresaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresaDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaDiaActionPerformed

    private void botonGuardarYSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarYSalirActionPerformed
        // TODO add your handling code here:
        MenuOpcionesPrincipales m1 = new MenuOpcionesPrincipales();
        if(validarIngresoNombre()&&validarIngresoApellidos()&&validarNumeroContacto()&&validarIngresoNacionalidad()&&validarIngresoDestino()&&validarIngresoCiudadOrigen()&&validarEmail()&&validarFecha()&&validarNumeroVuelo())
        {
        Pasajero pasajero = new Pasajero(ingresoNombres.getText(), ingresoApellidos.getText(), ingresoNacionalidad.getText(), ingresoCiudadPasajero1.getText(), ingresoEmail.getText(), ingresoNumContacto.getText(), MenuOpcionesPrincipales.numeroPasaporteRegistrar, validarGenero(), ingresoDestinoPasajero.getText());       
        Sintomatologia sintomatologia = new Sintomatologia(validarFiebre(), validarDolorCabeza(), validarMalestar(), validarDificultadRespiratoria(),validarTos());
        Date fechaPruebaPCR = new Date(Integer.parseInt(ingresaAnio.getText())-1900,Integer.parseInt(ingresaMes.getText())-1, Integer.parseInt(ingresaDia.getText()));
        PruebaPCR pruebaPCR = new PruebaPCR(fechaPruebaPCR, validarResultadoPrueba());
        Avion avion = PantallaInicial.buscarVuelo(PantallaInicial.vuelos, Integer.parseInt(ingresoNumeroVuelo.getText()));
        Formulario formulario = new Formulario();
        PantallaInicial.agregarPasajero(PantallaInicial.pasajeros, pasajero);
        PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteRegistrar).setFormulario(formulario);
        PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteRegistrar).getFormulario().setSintomatologia(sintomatologia);
        PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteRegistrar).getFormulario().setPruebaPCR(pruebaPCR);
        PantallaInicial.buscarPasajero(PantallaInicial.pasajeros, MenuOpcionesPrincipales.numeroPasaporteRegistrar).getFormulario().setAvion(avion);
        this.setVisible(false);
        m1.setVisible(true);
        }else if (validarIngresoNombre()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE NOMBRES.");
        }else if(validarIngresoApellidos()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE APELLIDOS.");
        }else if(validarNumeroContacto()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE NUMERO DE CONTACTO.");
        }else if(validarIngresoNacionalidad()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE NACIONALIDAD.");
        }else if(validarIngresoDestino()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE CIUDAD DE DESTINO.");
        }else if(validarIngresoCiudadOrigen()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE CIUDAD DE ORIGEN.");
        }else if(validarEmail()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE EMAIL.");
        }else if(validarFecha()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE FECHA.");
        }else if(validarNumeroVuelo()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE NUMERO DE VUELO.");
        }else{
            JOptionPane.showMessageDialog(null, "ERROR INESPERADO");
        }
    }//GEN-LAST:event_botonGuardarYSalirActionPerformed
    
    private void botonMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasculinoActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_botonMasculinoActionPerformed

    private void botonMasculinoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botonMasculinoStateChanged
        // TODO add your handling code here:
   

    }//GEN-LAST:event_botonMasculinoStateChanged

    private void botonFemeninoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botonFemeninoStateChanged
        // TODO add your handling code here:
    
        
    }//GEN-LAST:event_botonFemeninoStateChanged

    private void fiebreSiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fiebreSiStateChanged
        // TODO add your handling code here:
     
    }//GEN-LAST:event_fiebreSiStateChanged

    private void fiebreNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fiebreNoStateChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_fiebreNoStateChanged

    private void malestarSiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_malestarSiStateChanged
        // TODO add your handling code here:
  
    }//GEN-LAST:event_malestarSiStateChanged

    private void malestarNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_malestarNoStateChanged
        // TODO add your handling code here:
     
    }//GEN-LAST:event_malestarNoStateChanged

    private void dolorCabezaSiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dolorCabezaSiStateChanged
        // TODO add your handling code here:
   
    }//GEN-LAST:event_dolorCabezaSiStateChanged

    private void dolorCabezaNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dolorCabezaNoStateChanged
        // TODO add your handling code here:
  
    }//GEN-LAST:event_dolorCabezaNoStateChanged

    private void tosSiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tosSiStateChanged
        // TODO add your handling code here:
   
    }//GEN-LAST:event_tosSiStateChanged

    private void tosNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tosNoStateChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_tosNoStateChanged

    private void dificultadesSiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dificultadesSiStateChanged

    }//GEN-LAST:event_dificultadesSiStateChanged

    private void dificultadesNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dificultadesNoStateChanged
        // TODO add your handling code here:
     
    }//GEN-LAST:event_dificultadesNoStateChanged

    private void resultadoPositivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_resultadoPositivoStateChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_resultadoPositivoStateChanged

    private void resultadoNegativoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_resultadoNegativoStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_resultadoNegativoStateChanged

    private void ingresoNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoNombresFocusGained
        // TODO add your handling code here
        ingresoNombres.setText("INGRESE UN NOMBRE CUALQUIERA.Ej: Diego Jose");
    }//GEN-LAST:event_ingresoNombresFocusGained

    private void ingresoApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoApellidosFocusGained
        // TODO add your handling code here:
        ingresoApellidos.setText("INGRESE UN APELLIDO CUALQUIERA.Ej: Ocaña Sampedro");
    }//GEN-LAST:event_ingresoApellidosFocusGained

    private void ingresoNacionalidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoNacionalidadFocusGained
        // TODO add your handling code here:
        ingresoNacionalidad.setText("INGRESE SU NACIONALIDAD. Ej: Ecuatoriano");
    }//GEN-LAST:event_ingresoNacionalidadFocusGained

    private void ingresoDestinoPasajeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoDestinoPasajeroFocusGained
        // TODO add your handling code here:
        ingresoDestinoPasajero.setText("INGRESE SU CIUDAD DE DESTINO.Ej: Madrid");
    }//GEN-LAST:event_ingresoDestinoPasajeroFocusGained

    private void ingresoNumContactoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoNumContactoFocusGained
        // TODO add your handling code here:
        ingresoNumContacto.setText("INGRESE UN NUMERO DE MAXIMO 10 DIGITOS. Ej: 0992927124");
    }//GEN-LAST:event_ingresoNumContactoFocusGained

    private void ingresoCiudadPasajero1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoCiudadPasajero1FocusGained
        // TODO add your handling code here:
        ingresoCiudadPasajero1.setText("INGRESE LA CIUDAD DE DONDE PROVIENE. Ej: Guayaquil");
    }//GEN-LAST:event_ingresoCiudadPasajero1FocusGained

    private void ingresoNumeroVueloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoNumeroVueloFocusGained
        // TODO add your handling code here:
        ingresoNumeroVuelo.setText("INGRESE EL NUMERO DE SU VUELO: Ej: 123");
    }//GEN-LAST:event_ingresoNumeroVueloFocusGained

    private void ingresoNumeroVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNumeroVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNumeroVueloActionPerformed
/**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de nombres sea valido
     * @return boolean
     */
    public boolean validarIngresoNombre(){
        boolean validacion= true;
        if(ingresoNombres.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresoNombres.getText())==true){
            validacion = false;
        }
        return validacion;
        
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de apellidos sea valido
     * @return boolean
     */
    public boolean validarIngresoApellidos(){
        boolean validacion= true;
        if(ingresoApellidos.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresoApellidos.getText())==true){
            validacion = false;
        }
        return validacion;
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de nacionalidad sea valido
     * @return boolean
     */
    public boolean validarIngresoNacionalidad(){
        boolean validacion= true;
        if(ingresoNacionalidad.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresoNacionalidad.getText())==true){
            validacion = false;
        }
        return validacion;
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de ciudad destino sea valido
     * @return boolean
     */
    public boolean validarIngresoDestino(){
        boolean validacion= true;
        if(ingresoDestinoPasajero.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresoDestinoPasajero.getText())==true){
            validacion = false;
        }
        return validacion;
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de ciudad de origen sea valido
     * @return boolean
     */
    public boolean validarIngresoCiudadOrigen(){
        boolean validacion= true;
        if(ingresoCiudadPasajero1.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresoCiudadPasajero1.getText())==true){
            validacion = false;
        }
        return validacion;
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de genero
     * @return boolean
     */
    public boolean validarGenero(){
        boolean genero = true;
      //validacionGenero = 1;
      if(botonMasculino.isSelected()==true){
          genero = true;
      }
      else{ 
          genero = false;
      }
          return genero;
    }
      //}else if(botonMasculino.isSelected()== false && botonFemenino.isSelected() ==false){
      //validacionGenero = 0;
  
      
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de email sea valido
     * @return boolean
     */
    public boolean validarEmail(){
        Pattern rfc2822 = Pattern.compile("^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
					);
        boolean validacion= true;
        if(ingresoEmail.getText().isEmpty()==true){
            validacion = false;
        }
         //Bloque de validacion para email usando clases PATTERN y MATCHER
	if(!rfc2822.matcher(ingresoEmail.getText()).matches()) {
	validacion = false;
			} 
        return validacion;
    }
    /**
     * Metodo que retorna verdadero o falso segun lo ingresado en el campo de numero contacto sea valido
     * @return boolean
     */
    public boolean validarNumeroContacto(){
        boolean validacion= true;
        if(ingresoNumContacto.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresoNumContacto.getText())==false){
            validacion = false;
        }
        if(ingresoNumContacto.getText().length()<10 || ingresoNumContacto.getText().length()>15){
            validacion = false;
        }
        return validacion;
        
    }
    public boolean validarNumeroVuelo(){
        boolean validacion= true;
        if(ingresoNumeroVuelo.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresoNumeroVuelo.getText())==false){
            validacion = false;
        }
     try{
        if((PantallaInicial.buscarVuelo(PantallaInicial.vuelos,Integer.parseInt(ingresoNumeroVuelo.getText())) == null)){
            validacion = false;
        }
        }catch(NumberFormatException e){
        validacion = false;
        }
        return validacion;
        
    }
    /**
     * Metodo que retorna lo seleccionado para el atributo de fiebre
     * @return boolean
     */
    public boolean validarFiebre(){
      boolean validar = true;
      if(fiebreSi.isSelected()==true){
          validar= true;
      }else{
          validar = false;
        }
      return validar;
    }
 /**
     * Metodo que retorna lo seleccionado para el atributo de tos
     * @return boolean
     */
    public boolean validarTos(){
      boolean validar = true;
      if(tosSi.isSelected()){
          validar= true;
      }else{
          validar = false;
        }
      return validar;
    }
    /**
     * Metodo que retorna lo seleccionado para el atributo de malestar general
     * @return boolean
     */
    public boolean validarMalestar(){
       boolean validar = true;
      if(malestarSi.isSelected()){
          validar= true;
      }else{
          validar = false;
        }
      return validar;
    }
    /**
     * Metodo que retorna lo seleccionado para el atributo de dificultad respiratoria
     * @return boolean
     */
    public boolean validarDificultadRespiratoria(){
      boolean validar = true;
      if(dificultadesSi.isSelected()){
          validar= true;
      }else{
          validar = false;
        }
      return validar;
    }
    /**
     * Metodo que retorna lo seleccionado para el atributo de dolor de cabeza
     * @return boolean
     */
    public boolean validarDolorCabeza(){
       boolean validar = true;
      if(dolorCabezaSi.isSelected()){
          validar= true;
      }else{
          validar = false;
        }
      return validar;
    }
    /**
     * Metodo que retorna verdadero o false segun lo ingresado en los campos de fecha sean validos
     * @return boolean
     */
    public boolean validarFecha(){
        boolean validar = true;
        if((ingresaDia.getText().isEmpty()==false)&&PantallaInicial.isNumeric(ingresaDia.getText())==false){
            validar = false;
        }
        if(ingresaMes.getText().isEmpty()==false&&PantallaInicial.isNumeric(ingresaMes.getText())==false){
            validar = false;
        }
        if(ingresaAnio.getText().isEmpty()==false&&PantallaInicial.isNumeric(ingresaAnio.getText())==false){
            validar = false;
        }
        if((PantallaInicial.retornarNumero(ingresaDia.getText())==0)){
            validar = false;
        }else if(PantallaInicial.retornarNumero(ingresaDia.getText())<=0||PantallaInicial.retornarNumero(ingresaDia.getText())>31){
            validar = false;
        }
        if((PantallaInicial.retornarNumero(ingresaMes.getText())==0)){
            validar = false;
        }else if(PantallaInicial.retornarNumero(ingresaMes.getText())<=0||PantallaInicial.retornarNumero(ingresaMes.getText())>12){
            validar = false;
        }
        if((PantallaInicial.retornarNumero(ingresaAnio.getText())==0)){
            validar = false;
        }else if(PantallaInicial.retornarNumero(ingresaAnio.getText())<=2000||PantallaInicial.retornarNumero(ingresaAnio.getText())>2021){
            validar = false;
        }
        return validar;
    }
    /**
     * Metodo que retorna lo seleccionado para el atributo de resultado
     * @return boolean
     */
    public boolean validarResultadoPrueba(){
       boolean validar = true;
      if(resultadoPositivo.isSelected()){
          validar= true;
      }else{
          validar = false;
        }
      return validar;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPasajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonFemenino;
    private javax.swing.JButton botonGuardarYSalir;
    private javax.swing.JRadioButton botonMasculino;
    private javax.swing.JRadioButton dificultadesNo;
    private javax.swing.JRadioButton dificultadesSi;
    private javax.swing.JRadioButton dolorCabezaNo;
    private javax.swing.JRadioButton dolorCabezaSi;
    private javax.swing.JRadioButton fiebreNo;
    private javax.swing.JRadioButton fiebreSi;
    private javax.swing.ButtonGroup grupoBotoesDolorCabeza;
    private javax.swing.ButtonGroup grupoBotonesDificultades;
    private javax.swing.ButtonGroup grupoBotonesFiebre;
    private javax.swing.ButtonGroup grupoBotonesGenero;
    private javax.swing.ButtonGroup grupoBotonesMalestar;
    private javax.swing.ButtonGroup grupoBotonesResultado;
    private javax.swing.ButtonGroup grupoBotonesTos;
    private javax.swing.JTextField ingresaAnio;
    private javax.swing.JTextField ingresaDia;
    private javax.swing.JTextField ingresaMes;
    private javax.swing.JTextField ingresoApellidos;
    private javax.swing.JTextField ingresoCiudadPasajero1;
    private javax.swing.JTextField ingresoDestinoPasajero;
    private javax.swing.JTextField ingresoEmail;
    private javax.swing.JTextField ingresoNacionalidad;
    private javax.swing.JTextField ingresoNombres;
    private javax.swing.JTextField ingresoNumContacto;
    private javax.swing.JTextField ingresoNumeroVuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNacionalidad;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel labelNumContacto;
    private javax.swing.JLabel labelNumeroVuelo;
    private javax.swing.JLabel labelTituloSintomatologia;
    private javax.swing.JLabel logoTop;
    private javax.swing.JRadioButton malestarNo;
    private javax.swing.JRadioButton malestarSi;
    private javax.swing.JRadioButton resultadoNegativo;
    private javax.swing.JRadioButton resultadoPositivo;
    private javax.swing.JRadioButton tosNo;
    private javax.swing.JRadioButton tosSi;
    // End of variables declaration//GEN-END:variables
}
