/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaCliente;

import CapaNegocio.Avion;
import javax.swing.JOptionPane;

/**
 *
 * @author Czleb
 */
public class RegistrarVuelo extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVuelo
     */
    public RegistrarVuelo() {
        initComponents();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        logoTop = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ingresoCiudadProvieneVuelo = new javax.swing.JTextField();
        ingresoCiudadDestinoVuelo = new javax.swing.JTextField();
        ingresoHoraLlegadaVuelo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ingresoNumPasajerosVuelo = new javax.swing.JTextField();
        botonGuardarYSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("DATOS DE VUELO: (Ingrese los datos solicitados a partir de la informacion de su vuelo)");

        logoTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura.JPG"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Ciudad de donde proviene el vuelo:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Destino a donde se dirige:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Hora de llegada:");

        ingresoCiudadProvieneVuelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoCiudadProvieneVueloFocusGained(evt);
            }
        });

        ingresoCiudadDestinoVuelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoCiudadDestinoVueloFocusGained(evt);
            }
        });

        ingresoHoraLlegadaVuelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoHoraLlegadaVueloFocusGained(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Numero de pasajeros:");

        ingresoNumPasajerosVuelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ingresoNumPasajerosVueloFocusGained(evt);
            }
        });

        botonGuardarYSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonGuardarYSalir.setText("GUARDAR Y SALIR");
        botonGuardarYSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarYSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingresoHoraLlegadaVuelo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingresoCiudadDestinoVuelo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ingresoCiudadProvieneVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(ingresoNumPasajerosVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(logoTop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(botonGuardarYSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ingresoCiudadProvieneVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(ingresoNumPasajerosVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(ingresoCiudadDestinoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(ingresoHoraLlegadaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(botonGuardarYSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarYSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarYSalirActionPerformed
        // TODO add your handling code here:
        if(validarIngresoCiudadAvion()&&validarIngresoDestinoAvion()&&validarIngresoNumPasajerosAvion()&&validarIngresoHoraAvion()){
            Avion avion = new Avion(Integer.parseInt(ingresoNumPasajerosVuelo.getText()), ingresoHoraLlegadaVuelo.getText(), MenuOpcionesPrincipales.numeroVueloRegistrar, ingresoCiudadProvieneVuelo.getText(), ingresoCiudadDestinoVuelo.getText());
            PantallaInicial.agregarVuelo(PantallaInicial.vuelos, avion);
            MenuOpcionesPrincipales m1 = new MenuOpcionesPrincipales();
            this.setVisible(false);
            m1.setVisible(true);
        }else if(validarIngresoCiudadAvion()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE LA CIUDAD DE ORIGEN");
        }else if(validarIngresoDestinoAvion()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE LA CIUDAD DE DESTINO");
        }else if(validarIngresoNumPasajerosAvion()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DEL NUMERO DE PASAJEROS");
        }else if(validarIngresoHoraAvion()==false){
            JOptionPane.showMessageDialog(null, "ERROR EN EL CAMPO DE INGRESO DE LA HORA DE LLEGADA");
        }else{
            JOptionPane.showMessageDialog(null, "ERROR INESPERADO");
        }
        
    }//GEN-LAST:event_botonGuardarYSalirActionPerformed

    private void ingresoCiudadProvieneVueloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoCiudadProvieneVueloFocusGained
        // TODO add your handling code here:
        ingresoCiudadProvieneVuelo.setText("INGRESE LA CIUDAD DE DONDE PROVIENE EL VUELO");
    }//GEN-LAST:event_ingresoCiudadProvieneVueloFocusGained

    private void ingresoNumPasajerosVueloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoNumPasajerosVueloFocusGained
        // TODO add your handling code here:
        ingresoNumPasajerosVuelo.setText("INGRESE EL NUMERO DE PASAJEROS DEL VUELO");
    }//GEN-LAST:event_ingresoNumPasajerosVueloFocusGained

    private void ingresoCiudadDestinoVueloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoCiudadDestinoVueloFocusGained
        // TODO add your handling code here:
        ingresoCiudadDestinoVuelo.setText("INGRESE LA CIUDAD A DONDE SE DIRIGE EL VUELO");
    }//GEN-LAST:event_ingresoCiudadDestinoVueloFocusGained

    private void ingresoHoraLlegadaVueloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoHoraLlegadaVueloFocusGained
        // TODO add your handling code here:
        ingresoHoraLlegadaVuelo.setText("INGRESE LA HORA DE LLEGADA EN CUALQUIER FORMATO");
    }//GEN-LAST:event_ingresoHoraLlegadaVueloFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVuelo().setVisible(true);
            }
        });
    }

    
     public boolean validarIngresoCiudadAvion(){
        boolean validacion= true;
        if(ingresoCiudadProvieneVuelo.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresoCiudadProvieneVuelo.getText())==true){
            validacion = false;
        }
        return validacion;
    }
     public boolean validarIngresoDestinoAvion(){
        boolean validacion= true;
        if(ingresoCiudadDestinoVuelo.getText().isEmpty()==true){
            validacion = false;
        }
        if(PantallaInicial.isNumeric(ingresoCiudadDestinoVuelo.getText())==true){
            validacion = false;
        }
        return validacion;
    }
      public boolean validarIngresoHoraAvion(){
        boolean validacion= true;
        if(ingresoHoraLlegadaVuelo.getText().isEmpty()==true){
            validacion = false;
        }
        return validacion;
    }
      public boolean validarIngresoNumPasajerosAvion(){
        boolean validacion= true;
        if((ingresoNumPasajerosVuelo.getText().isEmpty()==false)&&PantallaInicial.isNumeric(ingresoNumPasajerosVuelo.getText())==false){
            validacion = false;
        }
        return validacion;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarYSalir;
    private javax.swing.JTextField ingresoCiudadDestinoVuelo;
    private javax.swing.JTextField ingresoCiudadProvieneVuelo;
    private javax.swing.JTextField ingresoHoraLlegadaVuelo;
    private javax.swing.JTextField ingresoNumPasajerosVuelo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel logoTop;
    // End of variables declaration//GEN-END:variables
}
